public class Test {
    public int test1(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }

    public int test2(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test3(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test4(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test5(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test6(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test7(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test8(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test9(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test10(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test11(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test12(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test13(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test14(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test15(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test16(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test17(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test18(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test19(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }
    public int test20(int param) {
        for(int i=0; i<10; i++) {
            param++;
        }
        return param;
    }

}