public class Test {
    public int test1(int param) {
        for(int i=0; i<10; i++) { // 1
            param++; // 2
        }
        return param;
    }

    public int test2(int param) {
        for(int i=0; i<10; i++) { // 3
            param++; // 4
        }
        return param;
    }
    public int test3(int param) {
        for(int i=0; i<10; i++) { // 5
            param++; // 6
        }
        return param;
    }
    public int test4(int param) {
        for(int i=0; i<10; i++) { // 7
            param++; // 8
        }
        return param;
    }
    public int test5(int param) {
        for(int i=0; i<10; i++) { // 9
            param++; // 10
        }
        return param;
    }
    public int test6(int param) {
        for(int i=0; i<10; i++) { // 11
            param++; // 12
        }
        return param;
    }
    public int test7(int param) {
        for(int i=0; i<10; i++) { // 13
            param++; // 14
        }
        return param;
    }
    public int test8(int param) {
        for(int i=0; i<10; i++) { // 15
            param++; // 16
        }
        return param;
    }
    public int test9(int param) {
        for(int i=0; i<10; i++) { // 17
            param++; // 18
        }
        return param;
    }
    public int test10(int param) {
        for(int i=0; i<10; i++) { // 19
            param++; // 20
        }
        return param;
    }
    public int test11(int param) {
        for(int i=0; i<10; i++) { // 21
            param++; // 22
        }
        return param;
    }
    public int test12(int param) {
        for(int i=0; i<10; i++) { // 23
            param++; // 24
        }
        return param;
    }
    public int test13(int param) {
        for(int i=0; i<10; i++) { // 25
            param++; // 26
        }
        return param;
    }
    public int test14(int param) {
        for(int i=0; i<10; i++) { // 27
            param++; // 28
        }
        return param;
    }
    public int test15(int param) {
        for(int i=0; i<10; i++) { // 29
            param++; // 30
        }
        return param;
    }
    public int test16(int param) {
        for(int i=0; i<10; i++) { // 31
            param++; // 32
        }
        return param;
    }
    public int test17(int param) {
        for(int i=0; i<10; i++) { // 33
            param++; // 34
        }
        return param;
    }
    public int test18(int param) {
        for(int i=0; i<10; i++) { // 35
            param++; // 36
        }
        return param;
    }
    public int test19(int param) {
        for(int i=0; i<10; i++) { // 37
            param++; // 38
        }
        return param;
    }
    public int test20(int param) {
        for(int i=0; i<10; i++) { // 39
            param++; // 40
        }
        return param;
    }

}
